# Indicates the configuration version (used by configuration migrations)
version: 4                                              
                              
# Home Assistant integration (MQTT discovery)           
homeassistant:                                     
    enabled: true

# permit join for new devices
permit_join: true
    # If you want to use the Home Assistant MQTT discovery, set this to true
    # and make sure that the base topic is set to zigbee2mqtt
    # https://www.zigbee2mqtt.io/integration/home_assistant.html#configuration
    # homeassistant: true                                                    
                                                             
# Enable the frontend, runs on port 8080 by default                   
frontend:                                                    
    enabled: true                                                     
    port: 8080                                               
                                                                      
# MQTT settings                                                                                
mqtt:                                                                                 
    # MQTT base topic for zigbee2mqtt MQTT messages                                            
    base_topic: zigbee2mqtt                                                           
    # MQTT server URL                                                                          
    server: 'mqtt://mosquitto:1883'                                                        
    # MQTT server authentication, uncomment if required:              
    # user: my_user                                                                            
    # password: my_password                                                           
                                                                      
# Serial settings, only required when Zigbee2MQTT fails to start with:                         
#   USB adapter discovery error (No valid USB adapter found).                         
#   Specify valid 'adapter' and 'port' in your configuration.         
serial:
  port: /dev/ttyUSB0
  adapter: ezsp    
#     # Location of the adapter                    
#     # USB adapters - use format "port: /dev/serial/by-id/XXX"
#     # Ethernet adapters - use format "port: tcp://192.168.1.12:6638"
#     port: /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED3DDF-if00
#     # Adapter type, allowed values: `zstack`, `ember`, `deconz`, `zigate` or `zboss`         
#     adapter: zstack                                                                 
                               
# Periodically check whether devices are online/offline        
# availability:                                                       
#     enabled: false                                                                           
                                                                                      
# Advanced settings        
advanced:                      
    channel: 15
    #log level for debugging, allowed values: debug, info, warn, error
    log_level: info                                                     
    # Let Zigbee2MQTT generate a network key on first start           
    network_key: GENERATE                                                                      
    # Let Zigbee2MQTT generate a pan_id on first start                                
    pan_id: GENERATE                                  
    # Let Zigbee2MQTT generate a ext_pan_id on first start     
    ext_pan_id: GENERATE                 